version: '3.7'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=talks
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=talksalot-db
    volumes:
      - talksalot_pg_data:/bitnami/postgresql

volumes:
  talksalot_pg_data:
